source 'http://rubygems.org'

gem 'rails', '3.2.17'

gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', ' ~> 3.2'
  gem 'coffee-rails', ' ~> 3.2'
  gem 'uglifier'
end

gem 'jquery-rails'
